version: '2'
services:
  mysql-development:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: znakomstva
    ports:
      - "3306:3306"
  admin:    
    image: adminer    
    ports:      
      - "8081:8081"
  web:
    build: .
    volumes:
      - .:/nsolum
    ports:
      - "8080:8080"
    depends_on:
      - "mysql-development"
    command: ["./wait-for-it.sh", "mysql-development:3306", "--", "python", "manage.py","runserver","0.0.0.0:8080"]